### ISSUE TITLE
Textbook script json fille

### ISSUE THREAD

**Issue by XiejiLi** [suinleelab/MONET#6]
Hi authors, thanks for the great work. 
When I run the pdf script in `src/MONET/preprocess/pdf_match.py`, I found a `data/textbook/pdf_files.config.json` is needed to extract text from pdf.
Could you provide your setting or the template of json file?
```
python src/MONET/preprocess/pdf_match.py \
--image data/textbook/pdf_extracted.compact.uncorrupted.dermonlyv3.hdf5 \
--pdf-extracted data/textbook/pdf_extracted \
--config data/textbook/pdf_files.config.json \
--output data/textbook/pdf_extracted.compact.uncorrupted.dermonlyv3.matched.pkl          
   path_config = Path(args.config)

``` 
    with open(path_config) as f:
        config = json.load(f)

    text_matched_all = []
    for pdf_name, pdf_config_list in config.items():

        for pdf_config in pdf_config_list:
            print(pdf_name, pdf_config)
            text_include_list = pdf_config["text_include_list"]
            fontsize_range = pdf_config["fontsize_range"]
            font_list = pdf_config["font_list"]
            prioritize_text_under_image = pdf_config["prioritize_text_under_image"]
            return_all = pdf_config["return_all"]
            key_images_pdf = [
                key
                for key in key_images
                if os.path.splitext(key)[0].split("_")[0] == pdf_name
                # and os.path.splitext(key)[0].split("_")[1] == "00742"
            ]
            # print(key_images_pdf)

            text_matched = match_text(
                path_base=path_pdf_extracted,
                key_images=key_images_pdf,
                text_include_list=text_include_list,
                fontsize_range=fontsize_range,
                font_list=font_list,
                prioritize_text_under_image=prioritize_text_under_image,
                return_all=return_all,
                verbose=False,
            )

**Comment by chanwkimlab** [comment]
Hi, thanks for your interest in our work! We've updated the repo to include the `data/textbook/template.config.json` file.

**Comment by XiejiLi** [comment]
Thank you.
